### PR TITLE
adding project ganjiang

### PR DESCRIPTION
**Pull request by dgquvn**

### CODE REVIEW

**Comment by jayjaybillings** [comment]
Good start. Thank you for your contribution. Before I can accept it I need you to amend your commit to add a signed-off-by statement. You can do this on the command line by executing:
```bash
git commit --amend --signoff
git push
```

**Comment by dgquvn** [comment]
Hello Jay,

Thank you for that.  I am not sure how to connect to the linux machine from offsite.  Let me know if you know how to do it.  Otherwise, I’ll wait until Monday.

Best regards,
Blueze

**Comment by jayjaybillings** [comment]
Hi Blueze. Thanks for signing off on the code. Here are some tasks that need to be completed before I will merge this: (Basically straight from the whiteboard...)

- [x] Split the code into multiple functions. Include a check for "\_\_main\_\_" at the bottom of the script ([see here](https://docs.python.org/2/library/__main__.html)) and put the rest of the code into one or more functions.
- [x] Create an arguments list that includes the names of the input and output files instead of hardwiring them as you have done at line 36 and 58. This argument list should be read in from, say, an INI or JSON file and checked before execution starts.
- [x] Remove the lines that are commented out
- [x] Double check to see if "Redraw()" is needed at line 39 and remove it if not.
- [x] Create a README file with instructions on how to use this code, including required dependencies and execution examples.
- [x] Let me know what you are thinking about unit tests

**Comment by dgquvn** [comment]
The current version is only supporting one merged geometry.  The complicated part is how to deal with different part geometry and how to assign material properties, which probably need occ package to do so.  Unit tests should be based on whether we do the current easy version or the complicated multi-body version

**Comment by jayjaybillings** [comment]
There are other things to test, like I/O for input processing of the parameter file, too.

?


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by dgquvn** [comment]
That also based on if the multi-body geometry is supported or not.  This is important because multi-body geometry configuration ini file could be totally different from one body geometry.  For instance, the material section, say there are two material for different part.  In that case, it is just not possible to set all the material information (E, nu, etc) in one configuration ini file.  The general way might be for a file path to the material information file.  If that's the case, I don't see the purpose of testing the parameters just based on the configuration of ini file.

**Comment by jayjaybillings** [comment]
Thanks for the updates. Here are some more tasks:

- [x] The content in __main__ should go into a separate function so that __main__ is minimal in size.
- [x] What are the ouput and Neutral Format values in the final part of the code? Should those not go into the configuration file?
- [x] ArgParse should be called parseArgs.
- [x] All function and variable names should follow a Camel Case format where the initial character is lowercase and the first letter of each new word is capitalized. parseArgs, readConfigFile, etc.

**Comment by dgquvn** [comment]
The output format is just for the mesh output and it can be neutral file, STL format, and etc, which you can find out from netgen graphic window export file types.  I don't think it is a good idea to put the export file information in the configuration file.  As I mentioned that to you before, the user only care about the import the step file and leave the rest for back-end process.  The only final result user may want is the exo file after Warp3D solvers finished the job

**Comment by jayjaybillings** [comment]
Here are two reasons we need to make the output configurable:
* The output file name needs to be reconfigurable *or* use a scheme that is predictable (output_\<date\> for example) so that we can produce a reasonable provenance trail. 
* The output type needs to be configurable so that we (or anyone) can use the tool for other problems without changing the source code.

We don't have to make either of these mandatory options for the user to configure. That is, we can accept default values for HPC4Mfg use cases, but have the ability to reuse this for other stuff. We need to go ahead and plan to make these changes, but if you want to talk about it more at work from a design perspective, just let me know.

**Comment by jayjaybillings** [comment]
I think something is wrong with the branch now. I see two files: AutoMeshScript.py and Auto_Mesh_Script.py. It looks like Auto_Mesh_Script.py has some of the old code in it.

That was probably caused by that Eclipse refresh bug. :-(

**Comment by jayjaybillings** [comment]
This looks very good. Accepted. Thanks Blueze!

**Review by jayjaybillings — COMMENTED** [review]
This addressed all of my comments in the main PR thread. There are several small things that we will change later, but overall this is good. I also find the use of some of the import statements to be very interesting - in a good way.

**Pull request merged**
